#!/bin/bash
#

CONF_PARAMS="--enable-evaluation"

if [ -e .coverage ]; then
	export CXXFLAGS="-g -O0 -Wall -W -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Woverloaded-virtual -Wwrite-strings -fprofile-arcs -ftest-coverage"
	export CFLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage"
	export LDFLAGS="-fprofile-arcs -ftest-coverage"

	./configure $CONF_PARAMS $@
else
	# configures the project to be verbose and pedantic to coding errors and mistakes. Additionally, debugging symbols are enabled.
	./configure CFLAGS="-ggdb -g3 -Wall -Wextra " $CONF_PARAMS $@
fi

